apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  database: ZGJuYW1l       # Base64 encoded dbname
  username: ZGRidXNlcg==   # Base64 encoded dbuser
  password: ZGRwYXNz       # Base64 encoded dbpass
  rootpassword: ZGRyb290cGFzcw== # Base64 encoded dbrootpass
